### ISSUE TITLE
You could add support for xcs 

### ISSUE THREAD

**Issue by Goles** [eraserhd/vim-ios#4]
I don't know if this is a good idea, but you could add support for [xcs](https://github.com/davidkovaccs/xcs) , or you could just take what they do there and integrate it in the vim-ios.

Basically it allows you to manipulate an Xcode project from the command line, so it would be a nice addition. 

Let me know what you think, if you can't find the time or don't want to interface with ruby, I could even try to help when I get a bit of time.

**Comment by eraserhd** [comment]
Thanks for the input!  I've started using a gem I'm taking over called zerg_xcode which has the same kind of functionality, except that it manipulates the file directly rather than uses Applescript.   The first feature which uses it has been on hold for a while, but the work is already in there.

Adding and removing files is definitely an important feature.
